### ISSUE TITLE
"Stop all drills" also stops science lab research

### ISSUE THREAD

**Issue by Suprcheese** [linuxgurugamer/AllYAll#1]
I have a lot of mods, but I've noticed that choosing "Stop all drills" on my mining base also stops all researching in the science lab. Perhaps science labs are also regarded as "Resource converters" so calling StopResourceConverter() also stops the research?

I've not tested in stock with just this mod, but steps to reproduce for me are:

1. Create a vessel with a science lab and drills
2. Deploy all drills
3. Activate all drills + activate research in the lab
4. Select the "Stop all drills" option on any of the drills

At this point, the drills will all stop as desired, but research in the lab will also be stopped -- unintended behavior for sure.

**Comment by linuxgurugamer** [comment]
Which science lab(s) are you seeing the problem on?

**Comment by linuxgurugamer** [comment]
No response after 5 years, closing this
