### ISSUE TITLE
Feature Request: Add "All" action to engines.

### ISSUE THREAD

**Issue by jh4c** [linuxgurugamer/AllYAll#10]
Copy/pasting what I hope are the important bits from the KSP forum thread:

"Is there a chance this could be expanded to engines, or would that involve too much fiddling around because of the larger risk of unintended consequences? I've been running some aircraft from the Stage 2 SPH (named action groups only, and they were all being used for stuff) and had cause to enable/disable my engines occasionally.

I would assume it would work the same as with other things, an extra button or two in the right-click menu for the affected parts.

Like I said, I recognise there could be unintended consequences if parts aren't recognised properly (shutting down drive and RCS engines, for example) and I don't expect any real effort to be expended on the idea if it's going to involve more than a couple of lines of code. However, I also recognise the possible utility that adding this to RCS engines could offer, especially with some of those ships you've been building in your streams recently; going from gross to fine control by shutting down a slew of engines could be accomplished by shutting them all off then re-enabling just the one or two blocks you want to keep active, which could save a lot of time and aggravation with setting up extra Action Groups (assuming a career is advanced enough to have access to them.)"

Presumably two checks would be required: 

- A) is it an engine;
- B) is it an RCS engine. 

If it passes the first check but fails the second, it's considered part of the Engines group. If it passes both, then it's added to the RCS group which is kept separate. (I guess you could also do the checks in the opposite order, in which case you could maybe have it so that passing the RCS check makes it skip the Engine check entirely.)

There's always going to be edge cases, but this mod is designed around broad strokes and those strike me as the two broadest ones when it comes to engines.

**Comment by linuxgurugamer** [comment]
To continue the discussion, what exactly would you want this to do?  My ideas are:

- Activate all engines
- Activate all engines in current stage
- Activate all engines connected to part
- Deactivate all engines
- Deactivate all engines in current stage
- Deactivate all engines connected to part
- Activate all RCS
- Deactivate all RCS
- Activate all RCS connected to part
- Deactivate all RCS connected to part

**Comment by jh4c** [comment]
As discussed on the forum, this is getting outside the scope of the mod's original intention. As such, I'm withdrawing the request.
