### ISSUE TITLE
Solar panels, radiators and other various parts display "toggle all SAS" as an option

### ISSUE THREAD

**Issue by Avera9eJoe** [linuxgurugamer/AllYAll#14]
Sorry for the vague details but it appears as though a handful of non-SAS parts also have "toggle all SAS" as an option when this mod is installed.

**Comment by linuxgurugamer** [comment]
you need to give a few details, I don't have time to go looking at all the parts

**Comment by Avera9eJoe** [comment]
Sounds good, I'll find some specific parts

**Comment by Avera9eJoe** [comment]
Strange. I can't seem to find any parts at the moment that have this bug now that I'm actively searching. It could be that its situational, or I was mistaken before. I'm closing the issue for now but if I find a specific example I'll open a new issue with it.

**Comment by dtoxic47** [comment]
sounds like some rouge MM patch maybe???
