### ISSUE TITLE
KeyNotFoundException in the AYA_RCS.cs.

### ISSUE THREAD

**Issue by BrettRyland** [linuxgurugamer/AllYAll#15]
I'm getting a KeyNotFoundException coming from the new RCS addition.
```
[EXC 00:49:45.968] KeyNotFoundException: The given key was not present in the dictionary.
  System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <9577ac7a62ef43179789031239ba8798>:0)
  AllYAll.AYA_RCS+<SlowUpdate>c__Iterator0.MoveNext () (at /var/lib/jenkins/workspace/A-F/AllYAll/Source/AYA_RCS.cs:423)
  UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2425394cf09642369e2109953e31f62b>:0)
  UnityEngine.DebugLogHandler:LogException(Exception, Object)
  ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
  UnityEngine.MonoBehaviour:StartCoroutine(String)
  AllYAll.AYA_RCS:Start() (at /var/lib/jenkins/workspace/A-F/AllYAll/Source/AYA_RCS.cs:380)
```

The line https://github.com/linuxgurugamer/AllYAll/blob/master/Source/AYA_RCS.cs#L423 needs to check that `stageParts` contains `curStage` (which can apparently happen from spawning vessels via BDArmory since we don't manage to properly restore the staging order) before performing that for-loop. There's a couple of other places in the file that will also need this check.

Also, apparently you released a debug build since I can get the line number from the stack trace. :-)

**Comment by linuxgurugamer** [comment]
As usual, please provide the entire player.log, not just a snippit.  My automated builds are not debug versions, I'm wondering where you got it from.  I did release a debug version before the full release

**Comment by linuxgurugamer** [comment]
In answer to your question, all my mods are compiled with the /debug flag which merely generates a file which contains the debugging information.  That file, which is shipped with the dll, is simply the dll file name with an added suffix of ".mdb", which the mono interpreter then uses to get the line numbers

**Comment by BrettRyland** [comment]
Sorry, I should know better about submitting logs with bug reports. Here's the [KSP.log](https://github.com/linuxgurugamer/AllYAll/files/14001129/KSP.log.txt) and [Player.log](https://github.com/linuxgurugamer/AllYAll/files/14001126/Player.log.txt) from a run where it happened (it was only happening about every 1 in 10 runs). I generally find the KSP.log file easier to work with.

I have AllYAll installed via CKAN. While you may have only published Release builds, I see you have debug symbols enabled for Release builds here: https://github.com/linuxgurugamer/AllYAll/blob/master/Source/AllYAll.csproj#L27C6-L27C15 due to specifying `<DebugType>pdbonly</DebugType>` (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype), which is why I'm able to get the line numbers since I'm usually running KSP with the development unity playback engine (https://forum.kerbalspaceprogram.com/topic/102909-ksp-plugin-debugging-and-profiling-for-visual-studio-and-monodevelop-on-all-os/).

Edit: ah, your reply above about the `/debug` flag came while I was writing this, so I didn't see it. Of note from the MS link above is:
> For all compiler versions starting with C# 6.0, there is no difference between pdbonly and full.

I'm not sure what effect that'll have on your mods in terms of performance, but I often don't see any difference between benchmarking in debug and release builds.

**Comment by linuxgurugamer** [comment]
Thank you.

As I said in the previous message, all my mods are compiled with the /debug flag which merely generates a file which contains the debugging information. That file, which is shipped with the dll, is simply the dll file name with an added suffix of ".mdb", which the mono interpreter then uses to get the line numbers.  It doesn't really affect performance at all.

You are actually the first person who ever was able to take advantage of this (to my knowledge).

I've implemented fixes, and will hopefully release an upgrade later today.

Just an FYI, the KSP.log and Player.log, while similiar, do show slightly different information in (occasionally) different order.  The Player.log is the more low-level log, which is why I prefer it, I have a local tool which helps me review it while getting rid of all the unnecessary fluff

**Comment by BrettRyland** [comment]
OK, thanks!

**Comment by BrettRyland** [comment]
Could the `Log.Error` on line 439 of AYA_RCS.cs be changed to report at most once or at least be reduced to a warning? My debug logs are now full of these errors
```
[ERR 00:11:36.165] AllYAll: Stage not found: 1 in stageParts.  This usually indicates a problem in a different mod
  UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
  ModuleManager.UnityLogHandle.InterceptLogHandler:LogFormat(LogType, Object, String, Object[])
  UnityEngine.Debug:LogError(Object)
  AllYAll.Log:Error(String) (at /var/lib/jenkins/workspace/A-F/AllYAll/Source/Log.cs:96)
  AllYAll.<SlowUpdate>c__Iterator0:MoveNext() (at /var/lib/jenkins/workspace/A-F/AllYAll/Source/AYA_RCS.cs:439)
  UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
and it needlessly fills the "Development Console".
![Screenshot_20240126_001856](https://github.com/linuxgurugamer/AllYAll/assets/18440126/d8bb2155-05e5-4ab4-a67e-67869e682ed2)
