### ISSUE TITLE
Science Experiments w/ mods

### ISSUE THREAD

**Issue by Davidj361** [linuxgurugamer/AllYAll#3]
The do all Science Experiments action doesn't work with modded science components I believe. The mod I have problems with was: DMagic Orbital Science. It would only do the vanilla science modules. I deployed the science modules and it still didn't work.

Can we get a config to disable this do all science action? Why? It just clutters my actions considering it doesn't work for all science modules.

**Comment by linuxgurugamer** [comment]
Or, maybe fix it?
I'll take a look

**Comment by linuxgurugamer** [comment]
All of the DMagic science experiments have now been added and released
