### ISSUE TITLE
Enhancement:  add fuel cells

### ISSUE THREAD

**Issue by Atario** [linuxgurugamer/AllYAll#4]
Please and thank you

**Comment by linuxgurugamer** [comment]
From which mod, or are these stock?

**Comment by linuxgurugamer** [comment]
And, what do you want to do, turn them on/off?

**Comment by linuxgurugamer** [comment]
Being worked on, maybe by the 25th

**Comment by Atario** [comment]
Yeah, turning on and off.  As for stock vs. mods, can it be done by detecting input/output conversion, to cover both stock and unknown mod parts?

**Comment by linuxgurugamer** [comment]
I'm simply loooking for resource convertors which have EC as output

**Comment by linuxgurugamer** [comment]
Released

**Comment by Atario** [comment]
Thanks, man!
